/**
 * 王国カードの初期枚数のパターン
 */
enum lowData {
    Victory = 8,
    Standard = 10,
    Gold = 30,
    Silver = 40,
    Copper = 46,
    Special = 1,
    Port = 12,
}

/**
 * 各カードの初期枚数
 */

export const initialCardCounts: { [key: string]: number } = {

    // ログ固有の用語
    card: 0,

    // 王国カード
    Province: lowData.Victory,
    Duchy: lowData.Victory,
    Estate: lowData.Victory,
    Gold: lowData.Gold,
    Silver: lowData.Silver,
    Copper: lowData.Copper,
    Curse: lowData.Standard,
    Potion: lowData.Standard,
    Platinum: lowData.Standard,
    Colony: lowData.Victory,


    //Dominion
    Cellar: lowData.Standard,
    Chapel: lowData.Standard,
    Moat: lowData.Standard,
    Harbinger: lowData.Standard,
    Merchant: lowData.Standard,
    Vassal: lowData.Standard,
    Village: lowData.Standard,
    Workshop: lowData.Standard,
    Bureaucrat: lowData.Standard,
    Gardens: lowData.Victory,
    Militia: lowData.Standard,
    Moneylender: lowData.Standard,
    Poacher: lowData.Standard,
    Remodel: lowData.Standard,
    Smithy: lowData.Standard,
    'Throne Room': lowData.Standard,
    Bandit: lowData.Standard,
    'Council Room': lowData.Standard,
    Festival: lowData.Standard,
    Laboratory: lowData.Standard,
    Library: lowData.Standard,
    Market: lowData.Standard,
    Mine: lowData.Standard,
    Sentry: lowData.Standard,
    Witch: lowData.Standard,
    Artisan: lowData.Standard,

    //Removedcards:
    Chancellor: lowData.Standard,
    Woodcutter: lowData.Standard,
    Feast: lowData.Standard,
    Spy: lowData.Standard,
    Thief: lowData.Standard,
    Adventurer: lowData.Standard,

    //Intrigue
    Courtyard: lowData.Standard,
    Lurker: lowData.Standard,
    Pawn: lowData.Standard,
    Masquerade: lowData.Standard,
    'Shanty Town': lowData.Standard,
    Steward: lowData.Standard,
    Swindler: lowData.Standard,
    'Wishing Well': lowData.Standard,
    Baron: lowData.Standard,
    Bridge: lowData.Standard,
    Conspirator: lowData.Standard,
    Diplomat: lowData.Standard,
    Ironworks: lowData.Standard,
    Mill: lowData.Victory,
    'Mining Village': lowData.Standard,
    'Secret Passage': lowData.Standard,
    Courtier: lowData.Standard,
    Duke: lowData.Victory,
    Minion: lowData.Standard,
    Patrol: lowData.Standard,
    Replace: lowData.Standard,
    Torturer: lowData.Standard,
    'Trading Post': lowData.Standard,
    Upgrade: lowData.Standard,
    Farm: lowData.Standard, // Assuming Farm is Harem from Intrigue 1E/2E differences? Harem is $6 Treasure-Victory. Farm is not listed directly in Intrigue 2E set.
    // Harem from Intrigue is listed as Nobles in 2E, or Harem if from Prosperity.
    // The original file has 'Farm: lowData.Standard' under Intrigue. This might be an error in the original file or a custom card.
    // For now, I will keep 'Farm' as is, as it's not in the transformation list.
    // Transformation list has Harem -> Harem, but there's no Harem key here under Intrigue.
    Nobles: lowData.Victory,

    //Removedcards:
    'Secret Chamber': lowData.Standard,
    'Great Hall': lowData.Standard,
    Coppersmith: lowData.Standard,
    Scout: lowData.Standard,
    Saboteur: lowData.Standard,
    Tribute: lowData.Standard,

    //Seaside
    Haven: lowData.Standard,
    Lighthouse: lowData.Standard,
    'Native Village': lowData.Standard,
    Astrolabe: lowData.Standard, // Not in transformation list, assuming it's correct or a new card
    'Fishing Village': lowData.Standard,
    Lookout: lowData.Standard,
    Monkey: lowData.Standard, // Not in transformation list
    'Sea Chart': lowData.Standard,
    Smugglers: lowData.Standard,
    Warehouse: lowData.Standard,
    Blockade: lowData.Standard, // Not in transformation list
    Caravan: lowData.Standard,
    Cutpurse: lowData.Standard,
    Island: lowData.Victory,
    Sailor: lowData.Standard, // Not in transformation list
    Salvager: lowData.Standard,
    TidePools: lowData.Standard, // Not in transformation list
    'Treasure Map': lowData.Standard,
    Bazaar: lowData.Standard,
    Corsair: lowData.Standard, // Not in transformation list
    'Merchant Ship': lowData.Standard,
    Outpost: lowData.Standard,
    Pirate: lowData.Standard, // Not in transformation list - note: Pirate Ship is separate
    'Sea Witch': lowData.Standard,
    Tactician: lowData.Standard,
    Treasury: lowData.Standard,
    Wharf: lowData.Standard,

    //Removedcards:
    Embargo: lowData.Standard,
    'Pearl Diver': lowData.Standard,
    Ambassador: lowData.Standard,
    Navigator: lowData.Standard,
    'Pirate Ship': lowData.Standard,
    'Sea Hag': lowData.Standard,
    Explorer: lowData.Standard,
    'Ghost Ship': lowData.Standard,

    //Alchemy
    'Transmute': lowData.Standard, // Assuming PTransmute -> Transmute
    Vineyard: lowData.Standard,
    Herbalist: lowData.Standard,
    Apothecary: lowData.Standard,
    'Scrying Pool': lowData.Standard,
    University: lowData.Victory,
    Alchemist: lowData.Standard,
    Familiar: lowData.Standard,
    "Philosopher's Stone": lowData.Standard,
    Golem: lowData.Standard,
    Apprentice: lowData.Standard,
    Possession: lowData.Standard,

    //Prosperity
    Anvil: lowData.Standard,
    Watchtower: lowData.Standard,
    Bishop: lowData.Standard,
    Clerk: lowData.Standard,
    Investment: lowData.Standard,
    Tiara: lowData.Standard,
    Monument: lowData.Standard,
    Quarry: lowData.Standard,
    "Worker's Village": lowData.Standard,
    Charlatan: lowData.Standard,
    City: lowData.Standard,
    Collection: lowData.Standard, // Not in transformation list
    'Crystal Ball': lowData.Standard,
    Magnate: lowData.Standard,
    Mint: lowData.Standard,
    Rabble: lowData.Standard,
    Vault: lowData.Standard,
    'War Chest': lowData.Standard,
    Hoard: lowData.Standard,
    'Grand Market': lowData.Standard,
    Bank: lowData.Standard,
    Expand: lowData.Standard,
    Forge: lowData.Standard,
    "King's Court": lowData.Standard,
    'Star Peddler': lowData.Standard,

    //Removedcards:
    Loan: lowData.Standard,
    'Trade Route': lowData.Standard,
    Talisman: lowData.Standard,
    Contraband: lowData.Standard,
    'Counting House': lowData.Standard,
    Mountebank: lowData.Standard,
    'Royal Seal': lowData.Standard,
    Venture: lowData.Standard,
    Goons: lowData.Standard,

    //Cornucopia&Guilds combined section
    'Candlestick Maker': lowData.Standard,
    Hamlet: lowData.Standard,
    Farrier: lowData.Standard, // Not in transformation list
    Stonemason: lowData.Standard,
    Menagerie: lowData.Standard,
    Shop: lowData.Standard, // Not in transformation list
    Infirmary: lowData.Standard, // Not in transformation list
    Advisor: lowData.Standard,
    Farmhands: lowData.Standard, // Not in transformation list
    Plaza: lowData.Standard,
    Remake: lowData.Standard,
    'Young Witch': lowData.Standard,
    Herald: lowData.Standard,
    Baker: lowData.Standard,
    Butcher: lowData.Standard,
    Carnival: lowData.Standard, // Not in transformation list
    Ferryman: lowData.Standard, // Not in transformation list
    Footpad: lowData.Standard, // Not in transformation list
    'Horn of Plenty': lowData.Standard,
    'Hunting Party': lowData.Standard,
    Jester: lowData.Standard,
    Journeyman: lowData.Standard,
    // JoustRewards -> Joust Rewards (is this for Joust itself, or its rewards? Prizes are separate)
    // Assuming Joust is the card, not JoustRewards. If JoustRewards is a collective term, it's not a card.
    // The transformation list has JoustRewards -> Joust Rewards. For now, I'll treat it as a card placeholder.
    'Joust': lowData.Standard, // Placeholder, might need specific handling if it's a category
    Coronet: lowData.Special, // Not in transformation list
    Courser: lowData.Special, // Not in transformation list
    Demesne: lowData.Special, // Not in transformation list
    Housecarl: lowData.Special, // Not in transformation list
    'Huge Turnip': lowData.Special,
    Renown: lowData.Special, // Not in transformation list
    'Merchant Guild': lowData.Standard,
    Soothsayer: lowData.Standard,
    Fairgrounds: lowData.Victory,

    //Removedcards from Cornucopia/Guilds:
    'Fortune Teller': lowData.Standard,
    Doctor: lowData.Standard,
    Masterpiece: lowData.Standard,
    'Farming Village': lowData.Standard,
    'Horse Traders': lowData.Standard,
    Taxman: lowData.Standard,
    'Tournament': lowData.Standard, // Assuming TournamentPrizes means the card Tournament that gives Prizes
    'Bag of Gold': lowData.Special,
    Diadem: lowData.Special,
    Followers: lowData.Special,
    Princess: lowData.Special,
    'Trusty Steed': lowData.Special,
    Harvest: lowData.Standard,

    //Hinterlands
    Crossroads: lowData.Standard,
    "Fools' Gold": lowData.Standard,
    Develop: lowData.Standard,
    'Guard Dog': lowData.Standard,
    Oasis: lowData.Standard,
    Scheme: lowData.Standard,
    Tunnel: lowData.Victory,
    'Jack of All Trades': lowData.Standard,
    Nomads: lowData.Standard, // Not in transformation list
    'Spice Merchant': lowData.Standard,
    Trader: lowData.Standard,
    Trail: lowData.Standard, // Not in transformation list
    Weaver: lowData.Standard, // Not in transformation list
    Berserker: lowData.Standard, // Not in transformation list
    Cartographer: lowData.Standard,
    Cauldron: lowData.Standard, // Not in transformation list
    Haggler: lowData.Standard,
    Highway: lowData.Standard,
    Inn: lowData.Standard,
    Margrave: lowData.Standard,
    Souk: lowData.Standard, // Not in transformation list
    Stables: lowData.Standard,
    Wheelwright: lowData.Standard, // Not in transformation list
    "Witch's Hut": lowData.Standard,
    'Border Village': lowData.Standard,
    Farmland: lowData.Victory,

    //Removedcards from Hinterlands:
    Duchess: lowData.Standard, // Corrected from Duches
    Oracle: lowData.Standard, // Corrected from racle
    'Noble Brigand': lowData.Standard,
    'Nomad Camp': lowData.Standard,
    'Silk Road': lowData.Victory,
    Cache: lowData.Standard,
    Embassy: lowData.Standard,
    'Ill-Gotten Gains': lowData.Standard,
    Mandarin: lowData.Standard,

    //DarkAges
    'Abandoned Mine': lowData.Standard, // from RuinsAbandonedMine
    'Ruined Library': lowData.Standard,
    'Ruined Market': lowData.Standard,
    'Ruined Village': lowData.Standard,
    Survivors: lowData.Standard,
    Spoils: lowData.Standard,
    'Poor House': lowData.Standard,
    Hovel: lowData.Standard, // from SheltersHovel
    Necropolis: lowData.Standard,
    'Overgrown Estate': lowData.Standard,
    Beggar: lowData.Standard,
    Squire: lowData.Standard,
    Vagrant: lowData.Standard,
    Forager: lowData.Standard,
    Hermit: lowData.Standard, // from HermitMadman
    'Market Square': lowData.Standard,
    Sage: lowData.Standard,
    Storeroom: lowData.Standard,
    Urchin: lowData.Standard, // from UrchinMercenary
    Armory: lowData.Standard,
    'Death Cart': lowData.Standard,
    Feodum: lowData.Victory,
    Fortress: lowData.Standard,
    Ironmonger: lowData.Standard,
    Marauder: lowData.Standard,
    Procession: lowData.Standard,
    Rats: lowData.Standard,
    Scavenger: lowData.Standard,
    'Wandering Minstrel': lowData.Standard,
    'Band of Misfits': lowData.Standard,
    'Bandit Camp': lowData.Standard,
    Catacombs: lowData.Standard,
    Count: lowData.Standard,
    Counterfeit: lowData.Standard,
    Cultist: lowData.Standard,
    Graverobber: lowData.Standard,
    'Junk Dealer': lowData.Standard,
    Knights: lowData.Standard,
    'Dame Anna': lowData.Special,
    'Dame Josephine': lowData.Special, // from Josephine
    'Dame Molly': lowData.Special, // from Molly
    'Dame Natalie': lowData.Special, // from Natalie
    'Dame Sylvia': lowData.Special, // from Sylvia
    'Sir Bailey': lowData.Special, // from SirsBailey
    'Sir Destry': lowData.Special, // from Destry
    'Sir Martin': lowData.Special, // from Martin
    'Sir Michael': lowData.Special, // from Michael
    'Sir Vander': lowData.Special, // from Vander
    Mystic: lowData.Standard,
    Pillage: lowData.Standard,
    Rebuild: lowData.Standard,
    Rogue: lowData.Standard,
    Altar: lowData.Standard,
    'Hunting Grounds': lowData.Standard,

    //Adventures
    'Coin of the Realm': lowData.Standard,
    Page: lowData.Standard,
    'Treasure Hunter': lowData.Standard,
    Warrior: lowData.Standard,
    Hero: lowData.Standard,
    Champion: lowData.Standard,
    Peasant: lowData.Standard,
    Soldier: lowData.Standard,
    Fugitive: lowData.Standard,
    Disciple: lowData.Standard,
    Teacher: lowData.Standard,
    Ratcatcher: lowData.Standard,
    Raze: lowData.Standard,
    Amulet: lowData.Standard,
    'Caravan Guard': lowData.Standard,
    Dungeon: lowData.Standard,
    Gear: lowData.Standard,
    Guide: lowData.Standard,
    Duplicate: lowData.Standard,
    Magpie: lowData.Standard,
    Messenger: lowData.Standard,
    Miser: lowData.Standard,
    Port: lowData.Port,
    Ranger: lowData.Standard,
    Transmogrify: lowData.Standard,
    Artificer: lowData.Standard,
    BridgeTroll: lowData.Standard,
    'Distant Lands': lowData.Victory,
    Giant: lowData.Standard,
    'Haunted Woods': lowData.Standard,
    'Lost City': lowData.Standard,
    Relic: lowData.Standard,
    'Royal Carriage': lowData.Standard,
    Storyteller: lowData.Standard,
    'Swamp Hag': lowData.Standard,
    'Treasure Trove': lowData.Standard,
    'Wine Merchant': lowData.Standard,
    Hireling: lowData.Standard,

    //Events (Adventures):
    Alms: lowData.Standard,
    Borrow: lowData.Standard,
    Quest: lowData.Standard,
    Save: lowData.Standard,
    'Scouting Party': lowData.Standard,
    'Travelling Fair': lowData.Standard,
    Bonfire: lowData.Standard,
    Expedition: lowData.Standard,
    Ferry: lowData.Standard,
    Plan: lowData.Standard,
    Mission: lowData.Standard,
    Pilgrimage: lowData.Standard,
    Ball: lowData.Standard,
    Raid: lowData.Standard,
    Seaway: lowData.Standard,
    Trade: lowData.Standard,
    'Lost Arts': lowData.Standard,
    Training: lowData.Standard,
    Inheritance: lowData.Standard,
    Pathfinding: lowData.Standard,

    //Empires
    Engineer: lowData.Standard,
    'City Quarter': lowData.Standard,
    Overlord: lowData.Standard,
    'Royal Blacksmith': lowData.Standard,
    Encampment: lowData.Standard,
    Plunder: lowData.Standard,
    Patrician: lowData.Standard,
    Emporium: lowData.Standard,
    Settlers: lowData.Standard,
    'Bustling Village': lowData.Standard,
    Castles: lowData.Standard, // This is a category, not a card. Humble Castle etc. are below.
    'Humble Castle': lowData.Standard,
    'Crumbling Castle': lowData.Standard,
    'Small Castle': lowData.Standard,
    'Haunted Castle': lowData.Standard,
    'Opulent Castle': lowData.Standard,
    'Sprawling Castle': lowData.Standard,
    'Grand Castle': lowData.Standard,
    "King's Castle": lowData.Standard,
    Catapult: lowData.Standard,
    Rocks: lowData.Standard,
    'Chariot Race': lowData.Standard,
    Enchantress: lowData.Standard,
    "Farmer's Market": lowData.Standard,
    Gladiator: lowData.Standard,
    Fortune: lowData.Standard,
    Sacrifice: lowData.Standard,
    Temple: lowData.Standard,
    Villa: lowData.Standard,
    Archive: lowData.Standard,
    Capital: lowData.Standard,
    Charm: lowData.Standard,
    Crown: lowData.Standard,
    Forum: lowData.Standard,
    Groundskeeper: lowData.Standard,
    Legionary: lowData.Standard,
    'Wild Hunt': lowData.Standard,

    //Events (Empires):
    Triumph: lowData.Standard,
    Annex: lowData.Standard,
    Donate: lowData.Standard,
    Advance: lowData.Standard,
    Delve: lowData.Standard,
    Tax: lowData.Standard,
    Banquet: lowData.Standard,
    Ritual: lowData.Standard,
    'Salt the Earth': lowData.Standard,
    Wedding: lowData.Standard,
    Windfall: lowData.Standard,
    Conquest: lowData.Standard,
    Dominate: lowData.Standard,

    //Landmarks:
    Aqueduct: lowData.Standard, // Aqueduct is a landmark, usually not counted in initialCardCounts this way.
    Arena: lowData.Standard,
    'Bandit Fort': lowData.Standard,
    Basilica: lowData.Standard,
    Baths: lowData.Standard,
    Battlefield: lowData.Standard,
    Colonnade: lowData.Standard,
    DefiledShrine: lowData.Standard,
    Fountain: lowData.Standard,
    Keep: lowData.Standard,
    Labyrinth: lowData.Standard,
    'Mountain Pass': lowData.Standard,
    Museum: lowData.Standard,
    Obelisk: lowData.Standard,
    Orchard: lowData.Standard,
    Palace: lowData.Standard,
    Tomb: lowData.Standard,
    Tower: lowData.Standard,
    'Triumphal Arch': lowData.Standard,
    Wall: lowData.Standard,
    'Wolf Den': lowData.Standard,

    //Nocturne
    "Will-o'-Wisp": lowData.Standard,
    Wish: lowData.Standard,
    Druid: lowData.Standard,
    'Faithful Hound': lowData.Standard,
    Guardian: lowData.Standard,
    Monastery: lowData.Standard,
    Pixie: lowData.Standard, // from PixieGoat
    Tracker: lowData.Standard, // from TrackerPouch
    Imp: lowData.Standard,
    Changeling: lowData.Standard,
    Fool: lowData.Standard, // from FoolLostintheWoods
    'Lucky Coin': lowData.Standard,
    'Ghost Town': lowData.Standard,
    Leprechaun: lowData.Standard,
    'Night Watchman': lowData.Standard,
    'Secret Cave': lowData.Standard,
    'Magic Lamp': lowData.Standard,
    Bard: lowData.Standard,
    'Blessed Village': lowData.Standard,
    Cemetery: lowData.Victory,
    'Haunted Mirror': lowData.Standard,
    Conclave: lowData.Standard,
    "Devil's Workshop": lowData.Standard,
    Exorcist: lowData.Standard,
    Necromancer: lowData.Standard,
    'Zombie Apprentice': lowData.Standard, // from ZombiesApprentice
    'Zombie Mason': lowData.Standard, // from ZombiesMason
    'Zombie Spy': lowData.Standard, // from ZombiesSpy
    Shepherd: lowData.Standard, // from ShepherdPasture
    Skulk: lowData.Standard,
    Ghost: lowData.Standard,
    Cobbler: lowData.Standard,
    Crypt: lowData.Standard,
    'Cursed Village': lowData.Standard,
    'Den of Sin': lowData.Standard,
    Idol: lowData.Standard,
    Pooka: lowData.Standard,
    'Cursed Gold': lowData.Standard,
    'Sacred Grove': lowData.Standard,
    Tormentor: lowData.Standard,
    'Tragic Hero': lowData.Standard,
    Vampire: lowData.Standard, // from VampireBat
    Werewolf: lowData.Standard,
    Raider: lowData.Standard,

    //Boons (These are typically not in initialCardCounts as buyable piles)
    "The Earth's Gift": lowData.Standard,
    "The Field's Gift": lowData.Standard, // From Field
    "The Flame's Gift": lowData.Standard, // From Flame
    "The Forest's Gift": lowData.Standard, // From Forest
    "The Moon's Gift": lowData.Standard, // From Moon
    "The Mountain's Gift": lowData.Standard, // From Mountain
    "The River's Gift": lowData.Standard, // From River
    "The Sea's Gift": lowData.Standard, // From Sea
    "The Sky's Gift": lowData.Standard, // From Sky
    "The Sun's Gift": lowData.Standard, // From Sun
    "The Swamp's Gift": lowData.Standard, // From Swamp
    "The Wind's Gift": lowData.Standard, // From Wind

    //Hexes (Also typically not in initialCardCounts as buyable piles)
    'Bad Omens': lowData.Standard,
    Delusion: lowData.Standard, // State
    Deluded: lowData.Standard, // State
    Envy: lowData.Standard, // from EnvyEnvious, Envious is state
    Famine: lowData.Standard,
    Fear: lowData.Standard,
    Greed: lowData.Standard,
    Haunting: lowData.Standard,
    Locusts: lowData.Standard,
    Misery: lowData.Standard, // State
    Miserable: lowData.Standard, // State
    'Twice Miserable': lowData.Standard, // State
    Plague: lowData.Standard,
    Poverty: lowData.Standard,
    War: lowData.Standard,

    //Renaissance
    'Border Guard': lowData.Standard,
    Horn: lowData.Standard, // Artifact
    Lantern: lowData.Standard, // Artifact
    Ducat: lowData.Standard,
    Lackeys: lowData.Standard,
    'Acting Troupe': lowData.Standard,
    'Cargo Ship': lowData.Standard,
    Experiment: lowData.Standard,
    Improve: lowData.Standard,
    'Flag Bearer': lowData.Standard,
    Flag: lowData.Standard, // Artifact
    Hideout: lowData.Standard,
    Inventor: lowData.Standard,
    'Mountain Village': lowData.Standard,
    Patron: lowData.Standard,
    Priest: lowData.Standard,
    Research: lowData.Standard,
    'Silk Merchant': lowData.Standard,
    'Old Witch': lowData.Standard,
    Recruiter: lowData.Standard,
    Scepter: lowData.Standard,
    Scholar: lowData.Standard,
    Sculptor: lowData.Standard,
    Seer: lowData.Standard,
    Spices: lowData.Standard,
    Swashbuckler: lowData.Standard,
    'Treasure Chest': lowData.Standard, // Artifact
    Treasurer: lowData.Standard,
    Key: lowData.Standard, // Artifact
    Villain: lowData.Standard,

    //Projects (Typically not in initialCardCounts as buyable piles)
    Cathedral: lowData.Standard,
    'City Gate': lowData.Standard,
    Pageant: lowData.Standard,
    Sewers: lowData.Standard,
    'Star Chart': lowData.Standard,
    Exploration: lowData.Standard,
    Fair: lowData.Standard,
    Silos: lowData.Standard,
    'Sinister Plot': lowData.Standard,
    Academy: lowData.Standard,
    Capitalism: lowData.Standard,
    Fleet: lowData.Standard,
    Guildhall: lowData.Standard,
    Piazza: lowData.Standard,
    'Road Network': lowData.Standard,
    Barracks: lowData.Standard,
    'Crop Rotation': lowData.Standard,
    Innovation: lowData.Standard,
    Canal: lowData.Standard,
    Citadel: lowData.Standard,

    //Menagerie
    'Black Cat': lowData.Standard,
    Sleigh: lowData.Standard,
    Supplies: lowData.Standard,
    'Camel Train': lowData.Standard,
    Goatherd: lowData.Standard,
    Scrap: lowData.Standard,
    Sheepdog: lowData.Standard,
    'Snowy Village': lowData.Standard,
    Stockpile: lowData.Standard,
    Horse: lowData.Standard,
    'Bounty Hunter': lowData.Standard,
    Cardinal: lowData.Standard,
    Cavalry: lowData.Standard,
    Groom: lowData.Standard,
    Hostelry: lowData.Standard,
    'Village Green': lowData.Standard,
    Barge: lowData.Standard,
    Coven: lowData.Standard,
    Displace: lowData.Standard,
    Falconer: lowData.Standard,
    Gatekeeper: lowData.Standard,
    'Hunting Lodge': lowData.Standard,
    Kiln: lowData.Standard,
    Livery: lowData.Standard,
    Mastermind: lowData.Standard,
    Paddock: lowData.Standard,
    Sanctuary: lowData.Standard,
    Fisherman: lowData.Standard,
    Destrier: lowData.Standard,
    Wayfarer: lowData.Standard,
    'Animal Fair': lowData.Standard,

    //Events (Menagerie):
    Delay: lowData.Standard,
    Desperation: lowData.Standard,
    Gamble: lowData.Standard,
    Pursue: lowData.Standard,
    Ride: lowData.Standard,
    Toil: lowData.Standard,
    Enhance: lowData.Standard,
    March: lowData.Standard,
    Transport: lowData.Standard,
    Banish: lowData.Standard,
    Bargain: lowData.Standard,
    Invest: lowData.Standard,
    'Seize the Day': lowData.Standard,
    Commerce: lowData.Standard,
    Demand: lowData.Standard,
    Stampede: lowData.Standard,
    Reap: lowData.Standard,
    Enclave: lowData.Standard,
    Alliance: lowData.Standard,
    Populate: lowData.Standard,

    //Ways (Typically not in initialCardCounts as buyable piles)
    'Way of the Butterfly': lowData.Standard,
    'Way of the Camel': lowData.Standard,
    'Way of the Chameleon': lowData.Standard,
    'Way of the Frog': lowData.Standard,
    'Way of the Goat': lowData.Standard,
    'Way of the Horse': lowData.Standard,
    'Way of the Mole': lowData.Standard,
    'Way of the Monkey': lowData.Standard,
    'Way of the Mouse': lowData.Standard,
    'Way of the Mule': lowData.Standard,
    'Way of the Otter': lowData.Standard,
    'Way of the Owl': lowData.Standard,
    'Way of the Ox': lowData.Standard,
    'Way of the Pig': lowData.Standard,
    'Way of the Rat': lowData.Standard,
    'Way of the Seal': lowData.Standard,
    'Way of the Sheep': lowData.Standard,
    'Way of the Squirrel': lowData.Standard,
    'Way of the Turtle': lowData.Standard,
    'Way of the Worm': lowData.Standard,

    //Allies (Cards from Allies expansion)
    Bauble: lowData.Standard,
    Sycophant: lowData.Standard,
    Townsfolk: lowData.Standard,
    'Town Crier': lowData.Standard,
    Blacksmith: lowData.Standard,
    Miller: lowData.Standard,
    Elder: lowData.Standard,
    Augurs: lowData.Standard,
    'Herb Gatherer': lowData.Standard,
    Acolyte: lowData.Standard,
    Sorceress: lowData.Standard,
    Sibyl: lowData.Standard,
    Clashes: lowData.Standard, // This might be a category, or a card
    'Battle Plan': lowData.Standard,
    Archer: lowData.Standard,
    Warlord: lowData.Standard,
    Territory: lowData.Standard,
    'Forts Tent': lowData.Standard, // Forts is likely category, Tent is card
    Garrison: lowData.Standard,
    HillFort: lowData.Standard, // Hill Fort
    Stronghold: lowData.Standard,
    Importer: lowData.Standard,
    'Merchant Camp': lowData.Standard,
    Odysseys: lowData.Standard, // This might be a category
    'Old Map': lowData.Standard,
    Voyage: lowData.Standard,
    'Sunken Treasure': lowData.Standard,
    'Distant Shore': lowData.Standard,
    Sentinel: lowData.Standard,
    Underling: lowData.Standard,
    Wizards: lowData.Standard, // This might be a category
    Student: lowData.Standard,
    Conjurer: lowData.Standard,
    Sorcerer: lowData.Standard,
    Lich: lowData.Standard,
    Broker: lowData.Standard,
    Carpenter: lowData.Standard,
    Courier: lowData.Standard,
    Innkeeper: lowData.Standard,
    'Royal Galley': lowData.Standard,
    Town: lowData.Standard,
    Barbarian: lowData.Standard,
    'Capital City': lowData.Standard,
    Contract: lowData.Standard,
    Emissary: lowData.Standard,
    Galleria: lowData.Standard,
    Guildmaster: lowData.Standard,
    Highwayman: lowData.Standard,
    Hunter: lowData.Standard,
    Modify: lowData.Standard,
    Skirmisher: lowData.Standard,
    Specialist: lowData.Standard,
    Swap: lowData.Standard,
    Marquis: lowData.Standard,

    //Allies (Ally type cards, typically not in initialCardCounts as buyable piles)
    "Architects' Guild": lowData.Standard,
    'Band of Nomads': lowData.Standard,
    'Cave Dwellers': lowData.Standard,
    'Circle of Witches': lowData.Standard,
    Citystate: lowData.Standard, // This is an Ally
    'Coastal Haven': lowData.Standard,
    "Crafters' Guild": lowData.Standard,
    'Desert Guides': lowData.Standard,
    'Family of Inventors': lowData.Standard,
    'Fellowship of Scribes': lowData.Standard,
    'Forest Dwellers': lowData.Standard,
    'Gang of Pickpockets': lowData.Standard,
    'Island Folk': lowData.Standard,
    'League of Bankers': lowData.Standard,
    'League of Shopkeepers': lowData.Standard,
    'Market Towns': lowData.Standard,
    'Mountain Folk': lowData.Standard,
    'Order of Astrologers': lowData.Standard,
    'Order of Masons': lowData.Standard,
    'Peaceful Cult': lowData.Standard,
    'Plateau Shepherds': lowData.Standard,
    "Trapper's Lodge": lowData.Standard,
    "Woodworkers' Guild": lowData.Standard,

    //Plunder
    Cage: lowData.Standard,
    Grotto: lowData.Standard,
    'Jewelled Egg': lowData.Standard,
    Search: lowData.Standard,
    Shaman: lowData.Standard,
    'Secluded Shrine': lowData.Standard,
    Siren: lowData.Standard,
    Stowaway: lowData.Standard,
    Taskmaster: lowData.Standard,
    Abundance: lowData.Standard,
    'Cabin Boy': lowData.Standard,
    Crucible: lowData.Standard,
    Flagship: lowData.Standard,
    'Fortune Hunter': lowData.Standard,
    Gondola: lowData.Standard,
    'Harbor Village': lowData.Standard,
    'Landing Party': lowData.Standard,
    Mapmaker: lowData.Standard,
    Maroon: lowData.Standard,
    Rope: lowData.Standard,
    'Swamp Shacks': lowData.Standard,
    Tools: lowData.Standard,
    'Buried Treasure': lowData.Standard,
    Crew: lowData.Standard,
    Cutthroat: lowData.Standard,
    Enlarge: lowData.Standard,
    Figurine: lowData.Standard,
    'First Mate': lowData.Standard,
    Frigate: lowData.Standard,
    Longship: lowData.Standard,
    'Mining Road': lowData.Standard,
    Pendant: lowData.Standard,
    Pickaxe: lowData.Standard,
    Pilgrim: lowData.Standard,
    Quartermaster: lowData.Standard,
    'Silver Mine': lowData.Standard,
    Trickster: lowData.Standard,
    'Wealthy Village': lowData.Standard,
    'Sack of Loot': lowData.Standard,
    "King's Cache": lowData.Standard,

    //Loots (Typically not in initialCardCounts as buyable piles)
    Amphora: lowData.Standard,
    Doubloons: lowData.Standard,
    'Endless Chalice': lowData.Standard,
    Figurehead: lowData.Standard,
    Hammer: lowData.Standard,
    Insignia: lowData.Standard,
    Jewels: lowData.Standard,
    Orb: lowData.Standard,
    'Prize Goat': lowData.Standard,
    'Puzzle Box': lowData.Standard,
    Sextant: lowData.Standard,
    Shield: lowData.Standard,
    'Spell Scroll': lowData.Standard,
    Staff: lowData.Standard,
    Sword: lowData.Standard,

    //Events (Plunder):
    Bury: lowData.Standard,
    Avoid: lowData.Standard,
    Deliver: lowData.Standard,
    Peril: lowData.Standard,
    Rush: lowData.Standard,
    Foray: lowData.Standard,
    Launch: lowData.Standard,
    Mirror: lowData.Standard,
    Prepare: lowData.Standard,
    Scrounge: lowData.Standard,
    Maelstrom: lowData.Standard,
    Journey: lowData.Standard,
    Looting: lowData.Standard,
    Invasion: lowData.Standard,
    Prosper: lowData.Standard,

    //Traits (Typically not in initialCardCounts as buyable piles)
    'Cheap': lowData.Standard, // Cheap is a Trait name
    Cursed: lowData.Standard, // This is a Trait name, distinct from Curse card
    Fated: lowData.Standard,
    Fawning: lowData.Standard,
    Friendly: lowData.Standard,
    Hasty: lowData.Standard,
    Inherited: lowData.Standard,
    Inspiring: lowData.Standard,
    Nearby: lowData.Standard,
    Patient: lowData.Standard,
    Pious: lowData.Standard,
    Reckless: lowData.Standard,
    Rich: lowData.Standard,
    Shy: lowData.Standard,
    Tireless: lowData.Standard,

    //RisingSun - Assuming this is a custom set or future expansion not yet widely known by this name
    'Mountain Shrine': lowData.Standard,
    Daimyo: lowData.Standard,
    Artist: lowData.Standard,
    Fishmonger: lowData.Standard,
    'Snake Witch': lowData.Standard,
    Aristocrat: lowData.Standard,
    Craftsman: lowData.Standard,
    Riverboat: lowData.Standard,
    'Root Cellar': lowData.Standard,
    Alley: lowData.Standard,
    Change: lowData.Standard,
    Ninja: lowData.Standard,
    Poet: lowData.Standard,
    'River Shrine': lowData.Standard,
    'Rustic Village': lowData.Standard,
    'Gold Mine': lowData.Standard,
    'Imperial Envoy': lowData.Standard,
    Kitsune: lowData.Standard,
    Litter: lowData.Standard,
    'Rice Broker': lowData.Standard,
    Ronin: lowData.Standard,
    Tanuki: lowData.Standard,
    'Tea House': lowData.Standard,
    Samurai: lowData.Standard,
    Rice: lowData.Standard,

    //Events (Rising Sun):
    Continue: lowData.Standard,
    Amass: lowData.Standard,
    Asceticism: lowData.Standard,
    Credit: lowData.Standard,
    Foresight: lowData.Standard,
    Kintsugi: lowData.Standard,
    Practice: lowData.Standard,
    'Sea Trade': lowData.Standard,
    'Receive Tribute': lowData.Standard,
    Gather: lowData.Standard,

    //Prophecies (Typically not in initialCardCounts as buyable piles)
    'Approaching Army': lowData.Standard,
    'Biding Time': lowData.Standard,
    Bureaucracy: lowData.Standard,
    'Divine Wind': lowData.Standard,
    Enlightenment: lowData.Standard,
    'Flourishing Trade': lowData.Standard,
    'Good Harvest': lowData.Standard,
    'Great Leader': lowData.Standard,
    Growth: lowData.Standard,
    'Harsh Winter': lowData.Standard,
    'Kind Emperor': lowData.Standard,
    Panic: lowData.Standard,
    Progress: lowData.Standard,
    'Rapid Expansion': lowData.Standard,
    Sickness: lowData.Standard,

    //Promo
    'Black Market': lowData.Standard,
    Church: lowData.Standard,
    Dismantle: lowData.Standard,
    Envoy: lowData.Standard,
    Sauna: lowData.Standard,
    Avanto: lowData.Standard,
    'Walled Village': lowData.Standard,
    Governor: lowData.Standard,
    Marchland: lowData.Standard, // Not in transformation list
    Stash: lowData.Standard,
    Captain: lowData.Standard, // Not in transformation list
    Prince: lowData.Standard,

    //Events (Promo):
    Summon: lowData.Standard,
    // Secondary cards from combined keys
    'Bat': lowData.Standard,
    'Envious': lowData.Standard,
    'Goat': lowData.Standard,
    'Lost in the Woods': lowData.Standard,
    'Madman': lowData.Standard,
    'Mercenary': lowData.Standard,
    'Pasture': lowData.Standard,
    'Pouch': lowData.Standard,
};
